### ISSUE TITLE
seg-fault for unbounded problem

### ISSUE THREAD

**Issue by soonhokong** [dreal/dreal_nra#2]
```
(set-logic QF_NRA)
(declare-fun x () Real)
(assert (= x (+ x 10.0)))
(check-sat)
(exit)
```

**Comment by soonhokong** [comment]
After fixing this, don't forget to try microfluidic benchmarks.

**Comment by soonhokong** [comment]
@scungao, this fixes the segmentation-fault problem. However, the above unbounded and simple example does not terminate (because of variable domain is [-oo, oo]?)

**Comment by scungao** [comment]
That shouldn't be the right behavior. I thought you were adding a linear pruning operator which should trivially return unsat on this?

**Comment by soonhokong** [comment]
Are you Sean for sure? You sounds like him though...

![screen shot 2015-01-30 at 9 54 54 am](https://cloud.githubusercontent.com/assets/403281/5977444/220c263e-a866-11e4-85ef-da2f2cf35c2d.png)

**Comment by soonhokong** [comment]
>  I thought you were adding a linear pruning operator which should trivially return unsat on this?

For the bounded cases, this version of dReal concludes UNSAT very quickly. Unfortunately, that is not the case for the unbounded problem.

**Comment by scungao** [comment]
I still get seg fault after updating, on this file:

(set-logic QF_NRA)
(declare-fun x () Real)
(assert (> x -100000))
(assert (< x 1000000))
(assert (= x (+ x 10.0)))
(check-sat)
(exit)

A previous binary (I think the test release one) of the nra branch was able to solve this problem. But if I delete the bounds, it (the binary from a previous version) says

dReal(59739,0x7fff74fae310) malloc: *** error for object 0x7fa1bac0c538: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

The current version returns seg fault on both files, the one with bounds and the one without bounds. 

But you said you can't reproduce the seg fault on your machine? I'm on mac air.

**Comment by soonhokong** [comment]
Can you try `ctest` in your build directory? If you get a bunch of failures, please do

```
rm lib/ include/ external
```

and then build it again. I think I had a similar problem and the above trick helped me.

**Comment by soonhokong** [comment]
FYI, I have UNSAT for the above instance (with bounds) in 0.014 sec.

**Comment by scungao** [comment]
Yes the new build fixes the problem. How can this happen? Perhaps add something in the build script to avoid this? (no rush on that)

**Comment by soonhokong** [comment]
Haha, good to know.

> How can this happen? Perhaps add something in the build script to avoid this? (no rush on that)

In short, you don't need to worry about. It's CMake which picks up the previously generated libraries with new flags (because I changed some link flags). In general, it shouldn't happen, esp, in a fresh checked-out source code.
